メールが重複した際にエラーメッセージが表示されるように修正
ryotaro-rks/ex-emp-management-bugfix pull request #5
Opened 2021-06-07 07:15 UTC by ryotaro-rks

2021-06-07 08:05 UTC, igamasayuki requested changes
修正依頼を出しましたので修正後Slackにてご連絡をお願いします。

2021-06-07 08:05 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
　(1-3)中級 Eメール重複チェック
model.addAttribute("duplicateMessage", "既に登録されているメールアドレスです");

ではなく、今回　resultにエラーメッセージを追加して、

viewでは

<label th:errors="*{mailAddress}" class="error-messages">
											メールアドレスを入力してください
</label>

で共通して必須入力のエラーメッセージと一緒にエラーメッセージを出すことができます。
BindingResultのAPIマニュアルを見ながら探してみてください。

2021-06-07 08:14 UTC, ryotaro-rks commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
レビューありがとうございます。修正いたします

2021-06-08 00:13 UTC, igamasayuki approved these changes
問題ありませんので承認します。

insert.htmlの59行目の以下が不要になるため削除してコミットしておきました。
<p th:text="${duplicateMessage}"></p>

履歴にて変更箇所をご確認ください。

2021-06-08 00:13 UTC, merged